### ISSUE TITLE
Revit plugin

### ISSUE THREAD

**Issue by mon-ami** [Autodesk-Forge/viewer-javascript-extract.spreadsheet#1]
Hello,
Any idea how to connect this solution to be used in a Revit plugin?
Thank you!

**Comment by cyrillef** [comment]
Is [this sample](https://github.com/Autodesk-Forge/model.derivative-csharp-context.menu) what you are looking for? If not, you would need to rewrite the code in C#, since C# can do REST calls, it will work the same way. You can make reference to RestSharp, Newtonsoft.Json and Autodesk.Forge on Nuget to simplify coding. We also got a C# sample posted [here](https://github.com/cyrillef/forge.wpf.csharp) and [here](https://github.com/Autodesk-Forge/model.derivative-csharp-context.menu)

**Comment by mon-ami** [comment]
Thanks a lot, I'm familiar with the first link, I'm just very new to this area and could not successfully run it locally so far, so I think I'm farther from applying it in a plugin. I just wanted to know if this JS project might be easier to start with.

**Comment by augustogoncalves** [comment]
this JavaScript version is intended to be integrated with an existing sample running on browser.

**Comment by mon-ami** [comment]
I don't want to open a new ticket, just asking for the rvt file that is in the example. Thank you!
